name: Run Robot Framework Purgo Malum API Tests

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Environment name'
        default: 'prod'
        required: true
        type: string
jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot Framework tests
        shell: pwsh
        run: |
          mkdir reports
          robot --outputdir reports tests/

      - name: Upload Robot Framework report
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-report
          path: reports/
