name: RunRestAssuredTestAutomation

on:
  workflow_dispatch:

jobs:
  test:
    name: Run REST Assured Tests (Maven)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Verify Java installation
        run: java -version

      - name: Build and Run REST Assured Tests
        run: mvn clean test --batch-mode

      - name: Archive Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/
